### ISSUE TITLE
Error "feature_float_get failed with error -3" when starting VimbaX ROS2 node

### ISSUE THREAD

**Issue by TejasKalsait** [alliedvision/vimbax_ros2_driver#1]
Our setup:

OS:                     Ubuntu 22.04 LTS
ROS2 Version:           Humble
Camera:                 Mako GigE       
VimbaX Software:         Installed and Camera is successfully detected (Tested using VimbaViewer)
Camera Firmware:        Updated using https://cdn.alliedvision.com/fileadmin/content/software/firmware/GigE/GigeFirmwareLoader-40111.zip

After following the installation steps, we attempted to run the command to start the ROS2 node:
`ros2 run vimbax_camera vimbax_camera_node`

We get the following error relat​ed to a feature:
`feature_float_get failed with error -3`
![PXL_20240604_221542598 MP](https://github.com/alliedvision/vimbax_ros2_driver/assets/69215615/9a4158aa-20df-461a-87df-d6f890367a8b)

**Comment by Masrur02** [comment]
Hi,

Have you solved the issue?

TIA

**Comment by dlangenkamp-avt** [comment]
Hi, 

At the Mako camera series the feature for read the current frame rate is not called "AcquisitionFrameRate". The get_camera_info function tries to always read this feature and fails, because it is not available.  As get_camera_info is called during initialization the node startup fails. 

You can use the following changes to fix the issue: https://github.com/alliedvision/vimbax_ros2_driver/pull/3/commits/bca291816d592296be690f2889ef8179837da4f3
Please be aware that this disables the frame rate read out and therefore also the camera info service will not return a valid value for the frame rate.

**Comment by TejasKalsait** [comment]
@Masrur02 Yes, we commented the lines 1421 to 1428 as pointed by @dlangenkamp-avt .

**Comment by Masrur02** [comment]
Hi,
Thanks. The issue is solved. May I know from where I can set the pixel format.

TIA

**Comment by Masrur02** [comment]
Hi,

The issue is solved. Thanks
