### ISSUE TITLE
Is 20.04 available?

### ISSUE THREAD

**Issue by zzapzzap** [alliedvision/vimbax_ros2_driver#2]
Hi, there.

We plan to migrate an environment: ROS2 from ROS1 (20.04).
Unfortunately, there is no 22.04 (For humble) BSP driver in Xavier AGX ORIN produced by [ConnectTech Co., Ltd.](https://connecttech.com/resource-center/l4t-board-support-packages/)
Would be no problem with test on ROS2 (For foxy) ubuntu 20.04?

Thank you

**Comment by dlangenkamp-avt** [comment]
Hi, 

currently only ROS 2 humble is supported. If you want to use another ROS 2 version, you can backport the driver yourself or send a request to support@alliedvision.com.
With NVIDIA Isaac ROS 2.1 it was possible to install ROS 2 humble on systems with Jetpack 5 (Ubuntu 20.04). As NVIDIA has released Isaac ROS 3 for Jetpack 6 (Ubuntu 22.04) the documentation of Issac ROS 2.1 is now longer available.  
But by cloning the [Isaac Github Pages Repository](https://github.com/NVIDIA-ISAAC-ROS/NVIDIA-ISAAC-ROS.github.io), checking out the branch "release-2.1" and than opening the index.html in a browser, you can still get the instructions how to install ROS 2 humble on Jetpack 5. Afterwards you can install the Vimba X ROS 2 driver arm64 debian package: [ros-humble-vimbax-camera-driver-1.0.0-amd64.deb](https://github.com/alliedvision/vimbax_ros2_driver/releases/download/v1.0.0/ros-humble-vimbax-camera-driver-1.0.0-amd64.deb). 
Otherwise you could also use the official ROS 2 humble docker container.

**Comment by zzapzzap** [comment]
Thank you for your comment.

It works well by using isaac ros (humble) !
So, I'll close the issue.

Have a nice day :)
